export const FIXED_FORM_SECTORS = [
  "FECHAMENTO",
  "SUCATA",
  "VAZAMENTO",
  "FORNO",
  "FUSÃO",
  "MACHARIA",
  "MOLDAGEM COLDBOX",
  "LINHA MOLDAGEM",
  "ACABAMENTO",
  "SOLDA",
  "TRATAMENTO TÉRMICO",
  "CQF",
  "MODELARIA",
  "USINAGEM",
  "MECÂNICA",
  "EXPEDIÇÃO",
  "MONTAGEM",
  "ALMOXARIFADO",
  "CQD",
  "REBOLO PENDULAR",
  "REBARBAÇÃO",
  "MAÇARICO",
  "LIXADEIRA MANUAL",
  "JATEAMENTO",
  "CORTE",
  "ACABAMENTO DE PEÇAS",
  "DESMOLDAGEM",
  "LINHA DE MOLDAGEM E FECHAMENTO",
  "MOLDAGEM",
  "MOLDES E MACHOS",
  "LOGÍSTICA INTERNA",
  "MANUTENÇÃO",
  "MARCENARIA",
  "DT",
  "QUALIDADE LABORATÓRIO",
  "AMBULATÓRIO",
  "COMPRAS",
  "FACILITES",
  "SEGURANÇA",
  "COMERCIAL",
  "RH",
  "PCP",
] as const;

const normalizeSectorKey = (value: string) =>
  value
    .normalize("NFD")
    .replace(/[\u0300-\u036f]/g, "")
    .replace(/[^a-zA-Z0-9 ]/g, " ")
    .replace(/\s+/g, " ")
    .trim()
    .toUpperCase();

const FIXED_SECTOR_MAP = new Map(
  FIXED_FORM_SECTORS.map((sector) => [normalizeSectorKey(sector), sector]),
);

const LEGACY_SECTOR_ALIASES: Record<string, (typeof FIXED_FORM_SECTORS)[number]> = {
  FECHAMENTO: "FECHAMENTO",
  SUCATA: "SUCATA",
  SUCUTA: "SUCATA",
  VAZAMENTO: "VAZAMENTO",
  FORNO: "FORNO",
  MACHARIA: "MACHARIA",
  "MOLDAGEM COLDBOX": "MOLDAGEM COLDBOX",
  "LINHA MOLDAGEM": "LINHA MOLDAGEM",
  "LINHA DE MOLDAGEM E FECHAMENTO": "LINHA DE MOLDAGEM E FECHAMENTO",
  ACABAMENTO: "ACABAMENTO",
  "ACABAMENTO DE PEÇAS": "ACABAMENTO DE PEÇAS",
  "ACABAMENTO DE PECAS": "ACABAMENTO DE PEÇAS",
  SOLDA: "SOLDA",
  "TRATAMENTO TERMICO": "TRATAMENTO TÉRMICO",
  "TRATAMENTO TÉRMICO": "TRATAMENTO TÉRMICO",
  FUSAO: "FUSÃO",
  "FUSÃO": "FUSÃO",
  CQF: "CQF",
  MODELARIA: "MODELARIA",
  "MODELAÇÃO": "MODELARIA",
  MODELACAO: "MODELARIA",
  USINAGEM: "USINAGEM",
  MECANICA: "MECÂNICA",
  "MECÂNICA": "MECÂNICA",
  EXPEDICAO: "EXPEDIÇÃO",
  "EXPEDIÇÃO": "EXPEDIÇÃO",
  EXPEDIO: "EXPEDIÇÃO",
  MONTAGEM: "MONTAGEM",
  ALMOXARIFADO: "ALMOXARIFADO",
  CQD: "CQD",
  REBOLOPENDULAR: "REBOLO PENDULAR",
  REBOLO: "REBOLO PENDULAR",
  REBARBACAO: "REBARBAÇÃO",
  REBARBAO: "REBARBAÇÃO",
  MACARICO: "MAÇARICO",
  LIXADEIRA: "LIXADEIRA MANUAL",
  JATEAMENTO: "JATEAMENTO",
  CORTE: "CORTE",
  "DESMOLDAGEM": "DESMOLDAGEM",
  "MOLDAGEM": "MOLDAGEM",
  "MOLDES E MACHOS": "MOLDES E MACHOS",
  "LOGISTICA INTERNA": "LOGÍSTICA INTERNA",
  MANUTENCAO: "MANUTENÇÃO",
  "MANUTENÇÃO": "MANUTENÇÃO",
  MARCENARIA: "MARCENARIA",
  DT: "DT",
  "QUALIDADE LABORATORIO": "QUALIDADE LABORATÓRIO",
  "QUALIDADE LABORATÓRIO": "QUALIDADE LABORATÓRIO",
  AMBULATORIO: "AMBULATÓRIO",
  "AMBULATÓRIO": "AMBULATÓRIO",
  COMPRAS: "COMPRAS",
  FACILITES: "FACILITES",
  SEGURANCA: "SEGURANÇA",
  "SEGURANÇA": "SEGURANÇA",
  COMERCIAL: "COMERCIAL",
  RH: "RH",
  PCP: "PCP",
};

export const resolveFixedSectorName = (value: unknown) => {
  const rawValue = value == null ? "" : String(value).trim();
  if (!rawValue) return "";

  const normalizedKey = normalizeSectorKey(rawValue);
  const directMatch = FIXED_SECTOR_MAP.get(normalizedKey);
  if (directMatch) return directMatch;

  const aliasedMatch = LEGACY_SECTOR_ALIASES[normalizedKey];
  if (aliasedMatch) return aliasedMatch;

  return rawValue;
};
